apiVersion: v1
kind: Service
metadata:
  name: fts3-artemis-stomp
  namespace: activemq-artemis-operator
  annotations:
    metallb.io/address-pool: sdf-rubin-ingest
    metallb.io/loadBalancerIPs: 172.24.10.101
spec:
  type: LoadBalancer
  ports:
    - port: 61613
      targetPort: 61613
      protocol: TCP
      name: fts3-artemis-stomp
  selector:
    application: fts3-artemis-app
  allocateLoadBalancerNodePorts: false
---
apiVersion: v1
kind: Service
metadata:
  name: fts3-artemis-console
  namespace: activemq-artemis-operator
  annotations:
    metallb.io/address-pool: sdf-rubin-ingest
spec:
  type: LoadBalancer
  ports:
    - port: 8161
      targetPort: 8161
      protocol: TCP
      name: fts3-artemis-console
  selector:
    application: fts3-artemis-app
  allocateLoadBalancerNodePorts: false

