apiVersion: apps/v1
kind: Deployment
metadata:
  name: fts3-mon
  labels:
    app: fts3-mon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fts3-mon
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: fts3-mon
    spec:
      volumes:
        - name: fts3-configs
          secret:
            defaultMode: 420
            secretName: fts3-configs
        - name: fts3-host-pems
          secret:
            defaultMode: 420
            secretName: fts3-host-pems
        - name: fts3-logs
          persistentVolumeClaim:
            claimName: fts3-logs-pvc
        - name: fts3web-libs-util
          configMap:
            name: fts3web-libs-util
        - name: sdf-group-rubin
          persistentVolumeClaim:
            claimName: sdf-group-rubin
      restartPolicy: Always
      initContainers:
      - name: prep-log-pvc
        image: ghcr.io/fnal-fife/fts3-mon:3.14.2
        imagePullPolicy: Always
        command: ["/bin/sh", "-c", "cp -r /var/log/* /out/"]
        volumeMounts:
          - name: fts3-logs
            mountPath: /out/
      containers:
        - name: httpd-error-logs
          image: busybox:latest
          imagePullPolicy: Always
          args: [/bin/sh, -c, 'tail -n+1 -F /var/log/httpd/fts3web_error_log']
          volumeMounts:
            - name: fts3-logs
              mountPath: /var/log
        - name: httpd-access-logs
          image: busybox:latest
          imagePullPolicy: Always
          args: [/bin/sh, -c, 'tail -n+1 -F /var/log/httpd/fts3web_access_log']
          volumeMounts:
            - name: fts3-logs
              mountPath: /var/log
        - name: fts3mon-logs
          image: busybox:latest
          imagePullPolicy: Always
          args: [/bin/sh, -c, 'tail -n+1 -F /var/log/fts3web/fts3web.log']
          volumeMounts:
            - name: fts3-logs
              mountPath: /var/log
        - name: fts3-mon
          image: ghcr.io/fnal-fife/fts3-mon:3.14.2
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 4Gi
          volumeMounts:
            - name: fts3-configs
              mountPath: /opt/fts3/fts3-configs
              readOnly: true
            - name: fts3-host-pems
              mountPath: /opt/fts3/fts3-host-pems
              readOnly: true
            - name: sdf-group-rubin
              mountPath: /etc/grid-security/certificates
              subPath: services/ddm/etc/grid-security/certificates
              readOnly: true
            - name: fts3-logs
              mountPath: /var/log
            - name: fts3web-libs-util
              mountPath: /usr/share/fts3web/libs/util.py
              subPath: util.py
          ports:
            - containerPort: 8449
              protocol: TCP
          env:
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: fts3-db
                  key: username
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fts3-db
                  key: password
            - name: MARIADB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: fts3-db
                  key: conn-str
            - name: FTS3_MARIADB_NAME
              valueFrom:
                secretKeyRef:
                  name: fts3-db
                  key: db-name
            - name: WEB_INTERFACE
              value: usdf-fts3-dev.slac.stanford.edu
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - mysql --host=${MARIADB_CONNECTION_STRING} -P 3306 --user=$MARIADB_USER --password="$MARIADB_PASSWORD" --database=fts3db -e 'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
