apiVersion: batch/v1
kind: Job
metadata:
  name: fetch-crl-on-install
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
        - args:
          name: fetch-crl
          image: ghcr.io/fnal-fife/fetch-crl-cron:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: ca-volume
              mountPath: /out/
          resources:
            requests:
              cpu: 256m
              memory: 500M
            limits:
              cpu: 256m
              memory: 500M
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30
      volumes:
        - name: ca-volume
          persistentVolumeClaim:
            claimName: grid-certificates-pvc
