namespace: fts3

resources:
  - ns.yaml
  - pvcs.yaml
  - deployment.yaml
  - fts3rest.yaml
  - fts3mon.yaml
  - service.yaml
  - cronjobs.yaml

secretGenerator:
  - name: fts3-configs
    options:
      disableNameSuffixHash: true
    files:
    - fts3config=etc/fts3config
    - fts3restconfig=etc/fts3restconfig
    - fts-activemq.conf=etc/fts-activemq.conf
  - name: fts3-host-pems
    options:
      disableNameSuffixHash: true
    files:
    - hostcert.pem=etc/secrets/hostcert.pem
    - hostkey.pem=etc/secrets/hostkey.pem
  - name: fts3-db
    options:
      disableNameSuffixHash: true
    files:
    - password=etc/secrets/fts3db-fts3-password
    - username=etc/secrets/fts3db-username
#    - conn-str=etc/secrets/fts3db-connection-string
    - conn-str=etc/secrets/fts3db-connection-string-cluster
    - db-name=etc/secrets/fts3db-name
  - name: fts-rest-entrypoint
    options:
      disableNameSuffixHash: true
    files:
    - docker-entrypoint.sh=etc/docker-entrypoint.sh
#  - name: fts3-activemq-secrets
#    options:
#      disableNameSuffixHash: true
#    files:
#      - broker_password=etc/temp_secrets/activemq/broker_password
#      - broker_username=etc/temp_secrets/activemq/broker_username
#      - broker_dns_alias=etc/temp_secrets/activemq/broker_dns_alias

configMapGenerator:
  - name: supervisord-conf
    files:
    - supervisord.conf=etc/supervisord.conf
  - name: fts3web-libs-util
    files:
    - util.py=etc/util.py
