apiVersion: v1
kind: Service
metadata:
  name: fts3-rest
  labels:
    app: fts3-rest
  namespace: fts3-rest
  annotations:
    metallb.io/address-pool: sdf-dmz
    #metallb.io/ip-allocated-from-pool: sdf-dmz
    metallb.io/loadBalancerIPs: 134.79.23.186
    metallb.io/allow-shared-ip: 134.79.23.186
spec:
  type: LoadBalancer
  ports:
    - port: 8446
      targetPort: 8446
      protocol: TCP
      name: fts3-rest
  selector:
    app: fts3-rest
  allocateLoadBalancerNodePorts: false
---
apiVersion: v1
kind: Service
metadata:
  name: fts3-mon
  labels:
    app: fts3-mon
  namespace: fts3-mon
  annotations:
    metallb.io/address-pool: sdf-dmz
    metallb.io/loadBalancerIPs: 134.79.23.186
    metallb.io/allow-shared-ip: 134.79.23.186
spec:
  type: LoadBalancer
  ports:
    - port: 8449
      targetPort: 8449
      protocol: TCP
      name: fts3-mon
  selector:
    app: fts3-mon
  allocateLoadBalancerNodePorts: false
