maxDiskUsage=90
connectionTtlOverride=120000

acceptorConfigurations.stomp.extraParams.heartBeatToConnectionTtlModifier=3.0
acceptorConfigurations.stomp.extraParams.stompMaxFramePayloadLength=1000000
acceptorConfigurations.stomp.extraParams.tcpKeepAlive=true

addressSettings.#.maxSizeMessages=1000
addressSettings.#.addressFullPolicy=BLOCK
addressSettings.#.deadLetterAddress=DLQ
addressSettings.#.expiryAddress=ExpiryQueue
addressSettings.#.autoCreateDeadLetterResources=true
addressSettings.#.autoCreateExpiryResources=true
addressSettings.#.deadLetterQueuePrefix=DLQ.
addressSettings.#.expiryQueuePrefix=EXP.
addressSettings.#.defaultQueueRoutingType=ANYCAST
addressSettings.#.defaultAddressRoutingType=MULTICAST
addressSettings.#.defaultRingSize=500000

addressConfigurations."fts_monitoring_complete.usdf_rucio".routingTypes=ANYCAST
addressConfigurations."fts_monitoring_complete.usdf_rucio".queueConfigs."fts_monitoring_complete.usdf_rucio".address=fts_monitoring_complete.usdf_rucio
addressConfigurations."fts_monitoring_complete.usdf_rucio".queueConfigs."fts_monitoring_complete.usdf_rucio".routingType=ANYCAST
addressConfigurations."fts_monitoring_complete.usdf_rucio".queueConfigs."fts_monitoring_complete.usdf_rucio".durable=true
addressConfigurations."fts_monitoring_complete.usdf_rucio_dev".routingTypes=ANYCAST
addressConfigurations."fts_monitoring_complete.usdf_rucio_dev".queueConfigs."fts_monitoring_complete.usdf_rucio_dev".address=fts_monitoring_complete.usdf_rucio_dev
addressConfigurations."fts_monitoring_complete.usdf_rucio_dev".queueConfigs."fts_monitoring_complete.usdf_rucio_dev".routingType=ANYCAST
addressConfigurations."fts_monitoring_complete.usdf_rucio_dev".queueConfigs."fts_monitoring_complete.usdf_rucio_dev".durable=false

divertConfigurations.copy-to-usdf-rucio.address=transfer.fts_monitoring_complete
divertConfigurations.copy-to-usdf-rucio.forwardingAddress=fts_monitoring_complete.usdf_rucio
divertConfigurations.copy-to-usdf-rucio.routingType=ANYCAST
divertConfigurations.copy-to-usdf-rucio.exclusive=false
divertConfigurations.copy-to-usdf-rucio-dev.address=transfer.fts_monitoring_complete
divertConfigurations.copy-to-usdf-rucio-dev.forwardingAddress=fts_monitoring_complete.usdf_rucio_dev
divertConfigurations.copy-to-usdf-rucio-dev.routingType=ANYCAST
divertConfigurations.copy-to-usdf-rucio-dev.exclusive=false

addressConfigurations."ActiveMQ.Advisory.TempQueue,ActiveMQ.Advisory.TempTopic".routingTypes=MULTICAST

divertConfigurations.divertTempQueueAdvisory.address=ActiveMQ.Advisory.TempQueue
divertConfigurations.divertTempQueueAdvisory.forwardingAddress=ActiveMQ.Advisory.TempQueue,ActiveMQ.Advisory.TempTopic
divertConfigurations.divertTempQueueAdvisory.exclusive=false

divertConfigurations.divertTempTopicAdvisory.address=ActiveMQ.Advisory.TempTopic
divertConfigurations.divertTempTopicAdvisory.forwardingAddress=ActiveMQ.Advisory.TempQueue,ActiveMQ.Advisory.TempTopic
divertConfigurations.divertTempTopicAdvisory.exclusive=false

addressConfigurations."ActiveMQ.Advisory.TempQueue,/topic/ActiveMQ.Advisory.TempTopic".routingTypes=MULTICAST

divertConfigurations.divertTempQueueAdvisory2.address=ActiveMQ.Advisory.TempQueue
divertConfigurations.divertTempQueueAdvisory2.forwardingAddress=ActiveMQ.Advisory.TempQueue,/topic/ActiveMQ.Advisory.TempTopic
divertConfigurations.divertTempQueueAdvisory2.exclusive=false

divertConfigurations.divertTempTopicAdvisory2.address=ActiveMQ.Advisory.TempTopic
divertConfigurations.divertTempTopicAdvisory2.forwardingAddress=ActiveMQ.Advisory.TempQueue,/topic/ActiveMQ.Advisory.TempTopic
divertConfigurations.divertTempTopicAdvisory2.exclusive=false
