apiVersion: apps/v1
kind: Deployment
metadata:
  name: fts3-activemq
  labels:
    app: fts3-activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fts3-activemq
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: fts3-activemq
    spec:
      volumes:
        - name: fts3-configs
          secret:
            defaultMode: 420
            secretName: fts3-configs
        - name: fts3-host-pems
          secret:
            defaultMode: 420
            secretName: fts3-host-pems
        - name: grid-certificates
          persistentVolumeClaim:
            claimName: grid-certificates-pvc
        - name: fts3-logs
          persistentVolumeClaim:
            claimName: fts3-logs-pvc
        - name: fts3-messages
          persistentVolumeClaim:
            claimName: fts3-messages-pvc
      restartPolicy: Always
      initContainers:
      - name: prep-log-pvc
        image: ghcr.io/fnal-fife/fts3-al9:3.14.2
        imagePullPolicy: Always
        command: ["/bin/sh", "-c", "cp -r /var/log/* /out/"]
        volumeMounts:
          - name: fts3-logs
            mountPath: /out/
      containers:
        - name: fts3
          image: ghcr.io/fnal-fife/fts3-activemq:3.14.4-s6-20260630
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
            - name: fts3-configs
              mountPath: /opt/fts3/fts3-configs
              readOnly: true
            - name: fts3-host-pems
              mountPath: /opt/fts3/fts3-host-pems
              readOnly: true
            - name: grid-certificates
              mountPath: /etc/grid-security/certificates
              readOnly: true
            - name: fts3-logs
              mountPath: /var/log
            - name: fts3-messages
              mountPath: /var/lib/fts3/messages
          env:
            - name: FTS3_BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fts3-activemq-secrets
                  key: FTS3_BROKER_PASSWORD
            - name: FTS3_BROKER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fts3-activemq-secrets
                  key: FTS3_BROKER_USERNAME
            - name: FTS3_BROKER_DNS_ALIAS
              valueFrom:
                secretKeyRef:
                  name: fts3-activemq-secrets
                  key: FTS3_BROKER_DNS_ALIAS
            - name: STOMP_PORT
              value: "61613"
