namespace: fts3

resources:
  - ns.yaml
  - pvcs.yaml
  - service.yaml
  - cronjobs.yaml
  - grid-certificates-job.yaml
  - fts3server.yaml
  - fts3mon.yaml
  - fts3rest.yaml
  - fts3activemq.yaml

secretGenerator:
  - name: fts3-configs
    options:
      disableNameSuffixHash: false
    files:
    - fts3config=etc/fts3config
    - fts3restconfig=etc/fts3restconfig
    - fts-activemq.conf=etc/fts-activemq.conf
  - name: fts3-server-config
    options:
      disableNameSuffixHash: false
    files:
    - fts3config=etc/fts3config
  - name: fts3-rest-config
    options:
      disableNameSuffixHash: false
    files:
    - fts3restconfig=etc/fts3restconfig
  - name: fts3-activemq-configs
    options:
      disableNameSuffixHash: false
    files:
    - fts3config=etc/fts3config
    - fts-activemq.conf=etc/fts-activemq.conf
  - name: fts3-host-pems
    options:
      disableNameSuffixHash: true
    files:
    - hostcert.pem=etc/secrets/hostcert.pem
    - hostkey.pem=etc/secrets/hostkey.pem
  - name: fts3-db
    options:
      disableNameSuffixHash: true
    files:
    - password=etc/secrets/fts3db-fts3-password
    - username=etc/secrets/fts3db-username
    - conn-str=etc/secrets/fts3db-connection-string
    - db-name=etc/secrets/fts3db-name
  - name: fts3-activemq-secrets
    options:
      disableNameSuffixHash: true
    envs:
      - etc/secrets/activemq-secrets

configMapGenerator:
  - name: fluent-bit-conf
    files:
    - fluent-bit.conf=etc/fluent-bit.conf
  - name: supervisord-conf
    files:
    - supervisord.conf=etc/supervisord.conf
