apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: fts3-db-cluster-2-backup
  namespace: fts3-db
spec:
  mariaDbRef:
    name: fts3-db-cluster
  databases:
    - fts3db
  args:
    - --verbose
  storage:
    persistentVolumeClaim:
      resources:
        requests:
          storage: 40Gi
      accessModes:
        - ReadWriteOnce
      storageClassName: wekafs--sdf-k8s01

